/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Akio
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmManutencao = new javax.swing.JMenu();
        jmDepartamentos = new javax.swing.JMenuItem();
        jmProdutos = new javax.swing.JMenuItem();
        jmRelatorios = new javax.swing.JMenu();
        jmRelatFiliais = new javax.swing.JMenuItem();
        jmEncaminhamentos = new javax.swing.JMenu();
        jmFiliais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmManutencao.setText("Manutenção");

        jmDepartamentos.setText("Departamentos");
        jmDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDepartamentosActionPerformed(evt);
            }
        });
        jmManutencao.add(jmDepartamentos);

        jmProdutos.setText("Produtos");
        jmManutencao.add(jmProdutos);

        jMenuBar1.add(jmManutencao);

        jmRelatorios.setText("Relatórios");

        jmRelatFiliais.setText("Filiais");
        jmRelatorios.add(jmRelatFiliais);

        jMenuBar1.add(jmRelatorios);

        jmEncaminhamentos.setText("Encaminhamentos");

        jmFiliais.setText("Filiais");
        jmEncaminhamentos.add(jmFiliais);

        jMenuBar1.add(jmEncaminhamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmDepartamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmDepartamentos;
    private javax.swing.JMenu jmEncaminhamentos;
    private javax.swing.JMenuItem jmFiliais;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenuItem jmProdutos;
    private javax.swing.JMenuItem jmRelatFiliais;
    private javax.swing.JMenu jmRelatorios;
    // End of variables declaration//GEN-END:variables
}
